# Generated by Django 6.0 on 2026-01-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftorder',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='draftorder',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='draftorder',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='draftorder',
            name='seller',
        ),
        migrations.AlterModelOptions(
            name='businessprofile',
            options={'verbose_name': 'business', 'verbose_name_plural': 'businesses'},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='broker_user_role_e2a23e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='broker_user_email_0027e0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'role'], name='broker_user_is_acti_e11531_idx'),
        ),
        migrations.DeleteModel(
            name='DraftOrder',
        ),
    ]
