# Generated by Django 6.0 on 2026-01-05 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_remove_draftorder_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdocument',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='broker.businessprofile'),
        ),
    ]
